### ISSUE TITLE
The dependency of Blackbox seems to be wrong on Thunderstore webpage

### ISSUE THREAD

**Issue by dakkidaze** [Velociraptor115/DSPMods#11]
![image](https://user-images.githubusercontent.com/13714426/162214487-3bac3cea-ffa6-4215-bd04-2e6bdb5312fc.png)
If I'm getting this right, the second dependency should be [CommonAPI](https://dsp.thunderstore.io/package/CommonAPI/CommonAPI/) by CommonAPI instead of [CommonAPI-DSPModSave](https://dsp.thunderstore.io/package/CommonAPI/DSPModSave/) by CommonAPI.
I installed the mod and it didn't work, in the log it says
```
[Error  :   BepInEx] Could not load [Blackbox 0.0.4] because it has missing dependencies: dsp.common-api.CommonAPI
```
manually downloading CommandAPI fixed the mod for me.

**Comment by Velociraptor115** [comment]
Thanks for bringing it to my attention
It seems I forgot to add CommonAPI as dependency after I used it for rebindable keybinds in version 0.0.4
Will update it in the next version
